WebApps/Controllers/LiveSessionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Model;
using WebApps.Helper;
using WebApps.Identity;
using WebApps.Models;
using WebApps.ViewModels;

namespace WebApps.Controllers
{
    
    public class LiveSessionsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
       // private readonly ILogger<HomeController> _logger;
        private readonly ILiveSessionService _liveSessionService;

        public LiveSessionsController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager, ILiveSessionService liveSessionService)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _liveSessionService = liveSessionService;
        }

        [HttpGet]
        public async Task<IActionResult> ListAllSessions()
        {
            IList<LiveSessionViewModel> webinar = new List<LiveSessionViewModel>();
            if (ModelState.IsValid)
            {
                var details = userManager.GetUserAsync(User);

                var Test1 = userManager.GetUserId(User);
                //string emailId = TempData["LoggedUser"].ToString();
                bool isLoggedIn = signInManager.IsSignedIn(User);
                LiveSession objliveSession = new LiveSession();

                if (isLoggedIn)
                {
                    string _primarySkill = details.Result.primarySkill;
                    string email = details.Result.Email;

                    IList<LiveSession> _result = await _liveSessionService.GetPrivateSession(_primarySkill);
                    if (_result.Count != 0)
                    {
                        foreach (var item in _result)
                        {
                            webinar.Add(new LiveSessionViewModel()
                            {
                                SId = item.SId,
                                description = item.description,
                                duration = item.duration,
                                isPrivate = item.isPrivate,
                                organiser = item.organiser,
                                Url = item.Url,
                                sessionCategory = item.sessionCategory
                            });
                        }

                        return View(webinar);
                    }
                    else 
                    {
                        TempData["NoSession"] = "You will soon see a private session here!";
                        return View(webinar);
                    }
                    
                }
                else
                {
                    return View();
                }
            }
            else 
            {
                return View(webinar);
            }
          
        }
    }
}

WebApps/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApps</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="font-weight: 800;font-size:30px;padding-right: 3%;" data-toggle="tooltip" data-html="true" title="<b>Career Development Portal</b>">CDP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 flex-sm-row-reverse">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button type="submit" class="btn btn-light" data-toggle="tooltip" data-html="true" title="<em>Click to</em> <b>LogOut</b>">LogOut</button>
                                </form>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="">@User.Identity.Name</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="homeLoginBtn" asp-controller="account" asp-action="Login">
                                    Login
                                </a>
                            </li>

                        }

                    </ul>
                    <ul id="Live_Privacy_NavBar" class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="LiveSessions" asp-action="ListAllSessions" data-toggle="tooltip" data-html="true" title="<em>Attend</em> <b>Live Sessions</b>">Attend Webinars</a>
                            @if (signInManager.IsSignedIn(User))
                                TempData["LoggedUser"] = User.Identity.Name;
                            else
                                TempData["LoggedUser"] = null;
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* ----------------- Footer Starts Here  ------------- *@
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 | E-Learning Portal | <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @* ------------------ Footer Ends Here *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)


    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
</body>
</html>